esphome:
  name: ir_bedroom
  platform: ESP8266
  board: esp_wroom_02
  includes: 
    - gree/gree_ir.h
  libraries:
    - IRremoteESP8266

wifi:
  ssid: ''            #Enter wifi ssid
  password:           #Enter wiwi password
  fast_connect: true

logger:

api:
  password: ''        #Enter api password

ota:
  password: ''        #Enter ota password

status_led:
  pin: GPIO4

remote_receiver:
  pin: 
    number: GPIO5
    inverted: true
  dump: all

remote_transmitter:
  pin: 
    number: GPIO14
    inverted: false
  carrier_duty_percent: 50%
  id: "ir_bedroom_transmitter"
    
climate:
- platform: custom
  lambda: |-
    auto bedroom_ac = new GreeAC();
    App.register_component(bedroom_ac);
    return {bedroom_ac};

  climates:
    - name: "Bedroom AC"
    
binary_sensor:
- platform: gpio
  pin:
    number: GPIO13
    inverted: true
  internal: true
  name: "ir_bedroom_button"
  id: "ir_bedroom_button"
    
switch:
- platform: custom
  lambda: |-
    auto gree_light_switch = new GreeLightSwitch();
    App.register_component(gree_light_switch);
    return {gree_light_switch};

  switches:
    name: "Bedroom AC light" 