substitutions:
  name: "smart-ir-remote-2"

esphome:
  name: "${name}"
  platform: ESP8266
  board: d1_mini
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_smartirremote_2
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet
  ap: 
    ssid: ${name}-AP
    password: !secret wifi_password
    ap_timeout: 3min
    
captive_portal:

logger:

api:

ota:
 
external_components:
  - source: local_components
    components: [ gree ]

climate:
- platform: gree
  name: "HVAC Head 2"
  pin: GPIO4
  visual:
    min_temperature: 10 °C
    max_temperature: 30 °C
    temperature_step: 1.0 °C
