esphome:
  name: "smart-ir-remote-1"
  platform: ESP8266
  board: d1_mini
  includes: 
    - gree/gree_ir.h
  libraries:
    - IRremoteESP8266
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
 
remote_transmitter:
  pin: 
    number: GPIO4
    inverted: false
  carrier_duty_percent: 50%
  id: "smart_ir_remote_1"

climate:
- platform: custom
  lambda: |-
    auto ac_head = new GreeAC();
    ac_head->set_temp_sensor(id(current_temperature));
    App.register_component(ac_head);
    return {ac_head};
  climates:
    - name: "HVAC Head 1"

sensor:
  - platform: homeassistant
    id: current_temperature
    entity_id: sensor.temperature