esphome:
  name: "smart-ir-remote-2"
  platform: ESP8266
  board: d1_mini
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
 
external_components:
  - source: local_components
    components: [ gree ]

climate:
- platform: gree
  name: "HVAC Head 2"
  pin: GPIO4
  visual:
    min_temperature: 10 °C
    max_temperature: 30 °C
    temperature_step: 1.0 °C
